CREATE TABLE "data".trigger (
	triggerid serial primary KEY,
	databucket int NOT NULL,
	trigger_filepath varchar(500) NOT NULL,
	wav_filename varchar(50),
	mf4_filename varchar(50),
	hostcam1_jpg varchar(50),
	hostcam2_jpg varchar(50),
	hostcam3_jpg varchar(50),
	hostcam4_jpg varchar(50),
	hostcam5_jpg varchar(50),
	hostcam6_jpg varchar(50),
	hostcam7_jpg varchar(50),
	hostcam8_jpg varchar(50),
	hostcam1_mp4 varchar(50),
	hostcam2_mp4 varchar(50),
	hostcam3_mp4 varchar(50),
	hostcam4_mp4 varchar(50),
	hostcam5_mp4 varchar(50),
	hostcam6_mp4 varchar(50),
	hostcam7_mp4 varchar(50),
	hostcam8_mp4 varchar(50),
	transcription_text varchar(2500),
	trigger_status varchar(500),
	trigger_package_creation_time timestamptz,
	truck_name varchar(50),
	cleaned_transcription varchar(2500),
	trigger_latitude varchar(500),
	trigger_longitude varchar(500),
	geolocation varchar(500)
	foreign key (databucketid) references data.trigger_jobqueue(databucketid)
);

CREATE TABLE "data".tags (
	triggerid int NOT NULL,
	databucketid int NOT NULL,
	tagid serial primary KEY,
	oaw bit,
	acc bit,
	mois bit,
	ala bit,
	dmc bit,
	asga bit,
	cc bit,
	ldw bit,
	mcs bit,
	xbr bit,
	sca bit,
	ldp bit,
	interurban bit,
	ipm bit,
	vrdu bit,
	tsr bit,
	aba bit,
	lka bit,
	dropout bit,
	failure bit,
	success bit,
	adas bit,
	xkrug bit,
	"forward target" bit,
	esa bit,
	"false positive" bit,
	good bit,
	poor bit,
	"air pressure" bit,
	"air supply" bit,
	rdf bit,
	uip bit,
	cta bit,
	dst bit,
	idle bit,
	"idle shutdown" bit,
	cpc bit,
	tagging_status varchar(100),
	foreign key (triggerid) references data.trigger(triggerid)
);

CREATE TABLE "data".trigger_jobqueue (
	databucketid int primary KEY,
	jobstatus varchar(100) NOT NULL,
	foreign key (databucketid) references data.file(id)
);
