from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification, DistilBertConfig, Trainer, TrainingArguments, EarlyStoppingCallback
from datasets import Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import fbeta_score
import numpy as np
import torch
import evaluate

print(torch.cuda.is_available())  # Should print: True
print(torch.cuda.get_device_name(0))  # Should print: NVIDIA A2000

#training data, showing clear distinction between content
examples = [
    # real data from previous transcriptions
    {"text": "Over a few hundred feet to curve, causing an LBP.", "label": 1},# engineering
    {"text": "Uphill grade, last hill over here. Yeah, what I did...", "label": 1}, 
    {"text": "Coming to standstill traffic or slowing down traffic will make you see", "label": 1}, 
    {"text": "So, Interurban, or Speed Permissive, SC, SCA.", "label": 1}, 
    {"text": "Investigate DNC false positives for a straw in a drink.", "label": 1}, 
    {"text": "Park Break is not identified by TTP.", "label": 1}, 
    {"text": "I got a trigger for a deer myth for a driver in front of us. Deer? Yeah. Yeah. Oh.", "label": 1}, 
    {"text": "and say like two seconds after light lane breaks, it drops in the... okay, it drops out.", "label": 1}, 
    {"text": "ATC maintaining 1.4 seconds following distance going downhill Too close", "label": 1}, 
    {"text": "S-Clicker triggered, ALA dropped out with no audible. No audible. What's that?", "label": 1}, 
    {"text": "Check engine light, stop lamp, and the sub mode. That's pretty much it.", "label": 1}, 
    {"text": "a copy from Driver while he was talking. What was that? Uh, ACC on slowing traffic. Engine brakes.", "label": 1}, 
    {"text": "Abandoned vehicle over the shoulder. He's working on mile post 55. Going triggered for TSR. 55 mile per hour sign visible and a 45 mile an hour sign visible.", "label": 1}, 
    {"text": "I got a trigger there. Another STA band. Oh, interesting. I didn't realize it goes to zero. There's like, when it goes to one foot, it goes zero, zero, one.", "label": 1}, 
    {"text": "Alright, ALA tried to make us go on the off-ramp.", "label": 1}, 
    {"text": "Trigger...uh...trigger note is IPM...most probable path.", "label": 1}, 
    {"text": "So the, so wait what happened so So the stop sign is geared up? Yeah, and what happened was it down to zero and then", "label": 1}, 
    {"text": "Radar unavailable possible obstruction pop-up.", "label": 1}, 
    {"text": "We've been driving for like, I don't know, at least three or four miles, and we only have like two temperatures. I mean, two pressures on our tire pressure.", "label": 1}, 
    {"text": "I just got a trigger for Driver infrastructure. Bridge. Bridge. Bridge. That's right. Bridge. Yeah.", "label": 1}, 
    {"text": "That was a very high, like, XPR ramp.", "label": 1}, 
    {"text": "Yeah, that's what we want, is to be... You want it to be, but it shouldn't match what the truck's units are set for? Your truck's units are set in metric or...", "label": 1}, 
    {"text": "Do a note for interurban with a right... Take a picture of that for Driver. Interurban. Yeah, we got it. Interurban for a right...", "label": 1}, 
    {"text": "I just took a trigger just for LDPs. Are you going to say LDPs? I don't know.", "label": 1}, 
    {"text": "Was the VRT exposed? It's active, right? What number is it?", "label": 1}, 
    {"text": "What's that? That seems like a brake. It didn't seem like a brake and very hard.", "label": 1}, 
    {"text": "Did you let some speeding happen? A little bit, yeah. And it released full brakes.", "label": 1}, 
    {"text": "Alright, we're in front of the wood, 20 inches.", "label": 1}, 
    {"text": "The caution screen in French, the hands-on screen in French is not available.", "label": 1}, 
    {"text": "No pop-up and it's UFPE as well.", "label": 1}, 
    {"text": "Speed limit too high, slow down, pop up. Cruise activated.", "label": 1}, 
    {"text": "Can you take a... I took a trigger, yeah. Um, ACC following closely, not too far.", "label": 1}, 
    {"text": "Super brief yellow pop-up that cleared itself to a deactivation tone. Wasn't sure if it was ALA or cruise. But then, um...", "label": 1}, 
    {"text": "I have a, I'm pretty sure it's an ALA deactivation with no tone.", "label": 1}, 
    {"text": "Second roundabout going straight. It's pretty tight so it takes wide and it takes close. Can you mark interurban left turn?", "label": 1}, 
    {"text": "We have Trigger, I would say, TSR, and with the ICA.", "label": 1}, 
    {"text": "The IPM, sorry, STA information was underneath the core target information. It's there again.", "label": 1}, 
    {"text": "So you see a right hand turn into the turn before it was there, straight down, essentially straight through the lens. No LDP, no LDP.", "label": 1}, 
    {"text": "End of trailer lines on while at highway speed.", "label": 1}, 
    {"text": "that it's changing to 60. Yeah, but this is a known limitation with TSR, unfortunately.", "label": 1}, 
    {"text": "Alright, I did get the LDP ended ALA timer.", "label": 1}, 
    {"text": "Unknown beepage. Beepage after going up a steep bump.", "label": 1}, 
    {"text": "Let me get a picture of that. It's for SDA.", "label": 1}, 
    {"text": "Can you make a note? Excessive yawning and no alert. Yeah, so we won't get any HMI.", "label": 1}, 
    {"text": "Why the **** are brakes faulted though?", "label": 1}, 
    {"text": "go to the next song, or press play, or pause, and it will, like the FM pad isn't doing any pressing. The button in the middle? Yeah.", "label": 1}, 
    {"text": "Yeah. Speaking to the mic? Yeah. Oh. The navigation button on the...", "label": 1}, 
    {"text": "Checking other routes. Right lane, turn into exit only, into exit 176. Another ICU C1. Transmission menu is also 1 out of 0.", "label": 1}, 
    {"text": "No optical warning on vehicle passing on the right hand side.", "label": 1}, 
    {"text": "I'm sorry. Um, optical warning on that bridge, guys.", "label": 1}, 
    {"text": "I think a lot of people are... So it seems like Cruise is giving us a tone every time we cancel at the service line.", "label": 1}, 
    {"text": "stopping a bit far away from target and stance in stop and go.", "label": 1}, 
    {"text": "That's a trigger for a patio, a wildlife corridor bridge. The truck on the right by a milestone.", "label": 1}, 
    {"text": "Trigger for voice off. You got that, Driver? Trigger for voice off.", "label": 1}, 
    {"text": "And just put yawn... Excessively? And then yawn. I'm really tired.", "label": 1}, 
    {"text": "It was kind of in the middle of the huge left and it was still going. Look, it's going right now. It's going to keep disconnecting on me.", "label": 1}, 
    {"text": "So on launching with the Xcel pedal, Oh man, that's rough. When launching on the Xcel pedal up this hill, I got a", "label": 1}, 
    {"text": "When you're going in reverse, weren't they saying there's something weird that can happen with the horizon line? Like going in reverse? With the camera? Yeah. That was something we had issues with down the BP-2. Typically, it only affected us at higher speed because we had good fallback for the radar only. Oh, sorry. We didn't really care about the camera at that point because I really didn't want to get in the way.", "label": 1}, 
    {"text": "Do you want... Yes. Selected. Regular cruise, yes. Now I have the correct logo for his regular cruise. And you fixed it. Is it back? Yep. Perfect. It didn't even touch you and then it came back. Beautiful. Didn't expect that. Excellent. So smart.", "label": 1}, 
    {"text": "15. Interesting. The seat belt doesn't care. Either the seat or the door open, it cares about. It's like, whoa, whoa, whoa, hold on. But the seat belt sensor is not a... It's rare that we have a trouble with the seat belt sensor, really. Yeah. It's rare. Really? Yeah, we don't do that very much. Yeah.", "label": 1}, 
    {"text": "Really fast. Oh, ****. Oh, ****. That one was bad. Um, so it was losing the target a whole bunch. I just plugged back in the MPC, I don't know if that's an issue, if it needs to be calibrated or anything like that. It needs to be calibrated. So that's something we were noticing though. It was never quite that bad. Uh huh. Like, one, the brakes are very sticky.", "label": 1}, 
    {"text": "The trigger didn't go. Okay, I got that one. I've had this happen previously, so if you want to just pop it in neutral, we're going to give it a little off on. Side guards just not available, okay. We're all happy. So, should we do it again? So this time, I'll have you avoid during the horn brake, which is so long it's pretty easy to hit me. So you want me to keep going straight in the lane? Straight lane, as soon as you feel braking, you can try to go around the parking lot. Don't hit the brake, just drive around. Any expected behavior? Expected behavior is cat's table stop. Which is, you know, the VRD, okay, it's not a critical object in your path anymore. You're going to go around the parking lot. You're going to stop beside the parking lot. Yeah. You should stop.", "label": 1}, 
    {"text": "Warning on the left side when changing lanes. No red warning. Need to get a better understanding of the logic on the left side.", "label": 1}, 
    {"text": "Pulse positive on light pole potentially.", "label": 1}, 
    {"text": "So I am experiencing what Driver experienced yesterday. I'm floored. I'm pedal to the metal. And I cannot accelerate.", "label": 1}, 
    {"text": "Good performance in merging lane situation for LA.", "label": 1},
    {"text": "That's where the hands-on detection was being tricked out by the too much friction residual torque.", "label": 1},
    {"text": "Now, there's one. Yeah, we're at the LDW Twitter. It's really in the beginning when we started.", "label": 1},
    {"text": "Target lane change speed control.", "label": 1},
    {"text": "The ACCU was trying to drive forward, but then it just... It couldn't pull up the hill.", "label": 1},
    {"text": "Yeah, the under shoot on the right hand curve, very slight.", "label": 1},
    {"text": "Thank you. Try to hit 5. Good for gear. I'm just halfway off the throttle. Okay. Two meters away. Okay. Two meters away. Okay. Two meters away.", "label": 1},
    {"text": "The more information tab overlaps with zero miles per hour when going to the more information menu when it's translated to Spanish.", "label": 1},
    {"text": "The time for an active call, the clock shows no zeros on the first digit of each.", "label": 1},
    {"text": "It went... it deactivated momentarily, and then came back. Okay. That... but why did it deactivate? Yeah. Um... Shit. Yeah. Momentarily deactivated. We're gonna get back. Another one up here. Another one up here, yeah.", "label": 1},
    {"text": "I put in this change? Do you remember that? So, when you override, basically the cascade stops. The warning is kind of going away, the optic acoustic, it won't start braking in that scenario. But when emergency brake would have started, it usually sends out another little beep beep. And it was never going to stop.", "label": 1},
    {"text": "Really? Are you happy with that one? Hmm, hmm, hmm, hmm. Yeah. What is the yellow? Is that the steering wheel? I think it was that one. That's the left one. That must be the right one. One is the wheel, one is the fusion, and the one is the R-rate. I just may not use that bright yellow one.", "label": 1},
    {"text": "So in the beginning of the next straight going into the intersection, do some kind of moderate braking going through your turnoff.", "label": 1},
    {"text": "There we go. We had four horn brake activations. I was going to say, because one of them felt like really long. The last one was definitely long. There was one that was more difficult.", "label": 1},
    {"text": "108 was my top there, but it wasn't too bad, not far from 100. Copy that. I think I was also starting to slow down. It's a 40 kph difference, but it doesn't seem that big when we're going half-back. Yeah, you want to try it again, or...? Yeah. Try it again.", "label": 1},
    {"text": "Oh look it's RDS, those STC's totally gone Oh man Maybe it's still available? No it's still gone There we go", "label": 1},
    {"text": "I'll reset it to 70 kph for 60, right? Yeah. Oh, oh, you're right. Okay. Yep, keep going. I'm gonna wait for you to leave the view. What is it? 60? Yep, yep. Perfect. Make up your mind, eh?", "label": 1},
    {"text": "with lane position at the right causing an LDP what do you write steering? D-E-E? Yep. steering to left with lane position on the right causing an LDP ya boi gracias what was that? gracias", "label": 1},
    {"text": "So we just lost ACC in 5420, I'm not sure what time it is.", "label": 1},
    {"text": "Intermittent loss of acceleration. Cruise control did not work at first. Had to pull over. Need to look at the data the last few minutes.", "label": 1},
    {"text": "Yeah. I took a trigger for, uh, false speed. I took a trigger for false speed. Yeah. False target.", "label": 1},
    {"text": "I just took a trigger there. Can you take a note that I got a pop up saying engage park brake? Yeah.", "label": 1},
    {"text": "Yeah, that was the one I saw on the curve. It's like I couldn't tell if it was target loss or just by the time you hit the back of the plane. Maybe do one for the following distance and then it would be high speed.", "label": 1},
    {"text": "I did two there. Engine brake maintained the following distance.", "label": 1},
    {"text": "MPC alignment shows radar alignment.", "label": 1},
    {"text": "Speed Curb Assist, MPP for most probable path. It thought that you were going to take a left here.", "label": 1},
    {"text": "We got kind of a weird ACC reaction. It decelerated.", "label": 1},
    {"text": "That's looking much better. 70 kph. Much better. No emergency brake. It's smoother. It's harsh. It's harsh in there though? We're getting minus 5 during our warn brake. So we're not getting any emergency brake because the warn brake is getting it all. Before the trailer was sucking down, the thin tire was mid the tractor was dying. Guess what we got running in here? What's that? Guess what we got running? A little else apparently. No, a pecan. Oh, so that's how you're making this all work? For Brian Matthew Phoenix? No, Miller. David, we're about to check wiring again. We're going to check wiring again. We might have to check some wires. I don't know where that's coming from but... So we are over pressuring the trailer. What? I think we got to check the wires. It's not working. It's not working. I don't know what it's doing. It's not working. It's not working. I don't know brilliantly. It's not working. It's not working. It's not working. It's not working. It's not working. It's not working. What are you doing over there?", "label": 1},
    {"text": "It doesn't give you a comfortable feeling for sure. It's too jerky. It makes you uncomfortable. Well, that was uncomfortable for me. I don't know about you. Oh.", "label": 1},
    {"text": "Okay, I'll probably go to the intersection here and wait for you when you guys are ready. Okay, copy that. It brakes a little harder than I would have. Yeah. So I heard on the 45X the new software is very hard. When it brakes, it brakes very hard. Really? Yeah. But it looks like that worked though, right? Yeah, it worked fine.", "label": 1},
    {"text": "It's probably long. Yeah, it is long. Okay, let's deactivate cruise. And let's try it one more time. Okay, and it's on. Yep. Okay.", "label": 1},
    {"text": "All very well. dismounted in 8 minutes. Helicopter heli VTI off. Thank you.", "label": 1},
    {"text": "We've been driving for like, I don't know, at least three or four miles, and we only have like two temperatures. I mean, two pressures on our tire pressure.", "label": 1},
    {"text": "It still gave me the O.I.W.", "label": 1},
    {"text": "I just got a trigger for Driver infrastructure. Bridge. Bridge. Bridge. That's right. Bridge. Yeah.", "label": 1},
    {"text": "Overshoot left. Copy. And a bridge. Straight here. That's 9380, I think.", "label": 1},
    {"text": "What's the later braking like? It went in, the L.A.W. went in and then it went out. Like I think it lost... That option? Yeah.", "label": 1},
    {"text": "Trigger, I can only try to kill him. Yeah, overshoot. That's a good data point. I mean, to me that's an understandable overshoot.", "label": 1},
    {"text": "And I just took another trigger. Seemed like false positive left side guard.", "label": 1},
    {"text": "ALA wanting to pull truck into left lane. Into the left curve? Left curve.", "label": 1},
    {"text": "There are so many of them. Just constant LDWs on car lines. You can figure? Yeah, yeah. Constant LDWs on car lines.", "label": 1},
    {"text": "Interesting. Cause look, I'm at a full lock right now and it was like, kind of veering that way.", "label": 1},
    {"text": "No tar lines. I don't even think there were tracks in the line. ADW, road hold time. I was at least a foot away from the lane light here.", "label": 1},
    {"text": "Yeah, hanging on the gears, not shifting, upshifting. Same thing.", "label": 1},
    {"text": "Alright, so that was the IPM event, probably Crest Coast.", "label": 1},
    {"text": "So it reset my cruise test speed again. And I'm certain of that. Like, I had a test at 65, and then", "label": 1},
    {"text": "I took a trigger, I peed off while driving, but ALA was on the whole time otherwise.", "label": 1},
    {"text": "We drove down in there and that's where he broke the truck. Just took a trigger for DMCA distraction. I'd say a valid one.", "label": 1},
    {"text": "I have safety monitor and pressure grade beginning. Alright, trigger time 22.26", "label": 1},
    {"text": "Okay, there was a pull out U-turn with the side, but nothing on TSR.", "label": 1},
    {"text": "I'm getting brake testing. So I got a trigger. The first, this one's ALA could barely hold a slight curve for this one.", "label": 1},
    {"text": "Tali, can you make another trigger for the vehicle not giving engine brakes when you're over the hysteresis top set point?", "label": 1},
    {"text": "Good morning. Thank you. So I just got a trigger for ALA overshot curve, like basically overshot.", "label": 1},
    {"text": "AVA unavailable. Again? I'm here. With no forward target.", "label": 1},
    {"text": "My glasses are polarized though, so... Probably not. Maybe false positive neon?", "label": 1},
    {"text": "Pop-up. Red pop-up. Here, I'm going to try navigation again. Have you hit the trigger? Yeah, I just hit one.", "label": 1},
    {"text": "Now I'm on a very gentle slope right now. It's 2% 3 so I Don't know why we're getting trashy control events", "label": 1},
    {"text": "So that was traction control events trying to go backwards up the hill.", "label": 1},
    {"text": "Yeah, so basically Interurban was slowing me down and it said that I had a stop sign up ahead coming.", "label": 1},
    {"text": "So again, overactive torque control slash oscillating torque control on steady slowing target.", "label": 1},
    {"text": "That was losing target in a slight left turn.", "label": 1},
    {"text": "Getting crazy wheel spin coming out of that belt. It's terrible. No traction control.", "label": 1},
    {"text": "So yeah, there was like a OEW audible without the EBA.", "label": 1},
    {"text": "the engine maintenance indicator timer, which reads dash 1.", "label": 1},
    {"text": "There's a mirror camera menu in the settings on the ICUC, but I can't go into it.", "label": 1},
    {"text": "Um, for testing the pre-fill though, because I could feel the trailer kick in. So that would be a good run for Driver to look at pressures. Yeah. So is that you braking yourself, or is that it braking? Uh, it brakes that time. That was a lot smoother. It must be learning from the previous run.", "label": 1},
    {"text": "Close by or over here? Oh, yeah, close by. It's interesting, you know, because I'm getting ASCA II events here, and it's funny because, like, you know, I'll have, like, a yellow warning, and then, like, as soon as you get to, like, right up in the back, I can, like, start to feel, you know, like, the vehicle steering. I don't know. It's really interesting, but at least we have one vehicle working. I am happy.", "label": 1},
    {"text": "You tell me... Not starting. Oh, she's not starting? Neutral. There it went, neutral all started.", "label": 1},
    {"text": "During braking on a vehicle, brake really soon and early possibly because the car is a couple of vehicles away, as well as the ICU seat is displayed a target after the car is already turned off. I'll do the cross street.", "label": 1},
    {"text": "40 kph, trigger box button, medium, red light on, the trigger switch on. Only one brake, no emergency brake. No hold brake.", "label": 1},
    {"text": "Finally able to get a red warning. The last few triggers have had no red warnings.", "label": 1},
    {"text": "Extremely good handling of hanging on situation on right hand turn of target.", "label": 1},
    {"text": "I got another trigger. AB-AB activation. And it was after putting my foot on the brake pedal. It started manually breaking down.", "label": 1},
    {"text": "Sorry, could you note a ASCA II event while changing lanes from the left? Sorry, 5420, we got a poorly timed TTC reset there. Hey, it really slowed us down. A-ASCA II event. Maybe just slightly intentional.", "label": 1},
    {"text": "Italian, that was for you. ALA decided to take the left hand lane. I don't know, it seems like we should auto-default to a right hand lane. Well, yeah, she was saying the source lane would be the right lane line, but was this like a right traffic keep right? This way? Yeah. What was it? One lane? Yeah.", "label": 1},
    {"text": "In the telephone settings, with my Bluetooth phone connected, there are no contact, dialed calls, receive calls, etc.", "label": 1},
    {"text": "No foundation breaking allowed during ATC.", "label": 1},
    {"text": "This one's just a note for Driver, B Coast with a forward target. And then when I lost the forward target, it exited B Coast. Exited B Coast.", "label": 1},
    {"text": "Curvature gain increased to 1.4. Some curves before.", "label": 1},
    {"text": "I'll turn MKA back on. Is that all the same stuff? I didn't get that right. Six meters away this time.", "label": 1},
    {"text": "one bearing, right curve, on the left side. LEP, one bearing, right curve, right hand curve.", "label": 1},
    {"text": "No call information on the incoming call on the ICU scene.", "label": 1},
    {"text": "Target lost upon entering curve. Would not reach tech for quite some time.", "label": 1},
    {"text": "Lost mid-curve, redetected toward accident curve, distance 2.6 seconds, all the way.", "label": 1},
    {"text": "Good detection of target and long range around curved winds. Side rails.", "label": 1}, 

    {"text": "A covered flood shortage is happening and as flood works with wet leaves are happening, there are more and more adventures, yay! But more accidents too, and right now, flood supplies are running low.", "label": 0},# not engineering
    {"text": "Excuse me, I didn't make a note of that. Is your diagnostic link parking? It should be. I don't know if the login is going to work. I guess I probably should have put it in.", "label": 0},
    {"text": "We'll see you next week.", "label": 0},    
    {"text": "I just held her with secrecy before the phone out, so she knew. Oh, yeah, okay. She knows it's my grandma's secret recipe. And now my grandmother's like, you let some temptress come in.", "label": 0},    
    {"text": "And then he opens the hood and he's looking around and he's like, where's all your airlines? Where's the brakes? I say, yep, this is very...", "label": 0},    
    {"text": "FYI, the weigh station is closed. 5420 is still going to pull in and do a sleep cycle. So, follow Sprinter, Hail Sprinter.", "label": 0},    
    {"text": "And, uh, but, usually scales you just roll through and nothing happens. Yeah. Um...", "label": 0},    
    {"text": "Can you, um, it felt like Driver just really wanted to push me to the right. That's correct. Um, as you were...", "label": 0},    
    {"text": "You guys do anything with the acres?", "label": 0},    
    {"text": "You're double whittled.", "label": 0},    
    {"text": "to have no physical fears. And those are interesting to drive. A lot better than drive-thru.", "label": 0},    
    {"text": "This pipe tuner looks pretty good but it is very slippery so I'll go voor via it.", "label": 0},    
    {"text": "Alright, that's good.", "label": 0},    
    {"text": "I was ready to make I want you in the first way", "label": 0},    
    {"text": "Visit PacificSourceMemberFirst.com The Bobcat National Sales Event is happening now at Bobcat of Central Oregon. Stop in and get a new Bobcat compact tractor.", "label": 0},    
    {"text": "I got my mind on you and you on my mind. Got you for you, but you ain't we could do tonight.", "label": 0},    
    {"text": "One more thing for the ground Hey, hey, hey Hey, senorita Don't you think we need a song To turn this on?", "label": 0},    
    {"text": "Thank you for listening to KWSO.", "label": 0},    
    {"text": "Alright, I think that worked.", "label": 0},    
    {"text": "I'll see you all in a while.", "label": 0},    
    {"text": "We'll be right back.", "label": 0},    
    {"text": "Aviators hiding me from the sun Old habits getting me down the highway It takes two when it", "label": 0},    
    {"text": "Real tough experience once again. But the last time I happened to tell a nice fight, and that was the best in 14 to red books.", "label": 0},    
    {"text": "I'm not touching anything under there, are you?", "label": 0},    
    {"text": "there was like a yellow, I don't know if it was a pool zone, or like it looked like a walking zone, and then it said, yeah, and then there was like", "label": 0},    
    {"text": "Yeah, much better than the other ones. That's nice.", "label": 0},    
    {"text": "That's going a little fast. Sorry, I don't think I noted it.", "label": 0},    
    {"text": "Ok, got bolt brake 2. Alright, that looks a lot better.", "label": 0},    
    {"text": "I think you did. But we have minus three now in the system, so I don't think we get...", "label": 0},    
    {"text": "What do you think your salary could be in the school system, whether it be private or local? What could you make? I think we would probably be looking at about $50-60.", "label": 0},    
    {"text": "right kept", "label": 0},    
    {"text": "Okay, that was the run. You got your trigger? I did, yeah. I'll help you in a second. What, Driver? I'm sorry.", "label": 0},    
    {"text": "by blocking and reflecting light. The UV radiation hits the particles and they get reflected. Along with the ultraviolet, which is not visible, it also reflects some visible light.", "label": 0},    
    {"text": "What is the difference? What ingredients do you have for... What belongs in the shopping basket? And what do you want to know from that round table?", "label": 0},    
    {"text": "So my CDL is, I think my, it might have been my first summer CDL.", "label": 0},    
    {"text": "and they can help you to isolate those products. Otherwise, you're playing a very difficult guessing game. Thank you. Have there been any advances in sunscreen?", "label": 0},    
    {"text": "The losses are not going to be spreading evenly. In fact, they're going to be concentrated in places that are already growing a lot of crops. So the breadbath is in the road and that doesn't mean that the crops are going to be in the way.", "label": 0},    
    {"text": "better at this point because as Driver says, Morbid Alley has been involved in a few incidents this year.", "label": 0},    
    {"text": "accounts 24-7, 365. 4% APY is not a promotional rate, and there's no limit to what you can deposit and earn. And it takes just minutes to transfer your cash.", "label": 0},    
    {"text": "It's just a frame when they were supposed to be told to turn it down and now it's... they have to go back to this book. Maybe it was the officer who was on the floor this week.", "label": 0},    
    {"text": "just like one or two points away from being a race plan. I mean, it's... And I get the point that you say, Pete. It's over minor things. Like, it's accumulation over a...", "label": 0},    
    {"text": "It's like the point that Driver makes about the whole, he's seen it his whole career, he knows what his brother can do. And it's like, yesterday as you say, Pete, get that.", "label": 0},    
    {"text": "I'd like to clarify that, but he still had some issues with his shoulder, you can see that. He qualified on fourth, and I thought, he's doing really good.", "label": 0},    
    {"text": "The clear thing is that you're given a rider penalty. If you take the penalty you get to go on the track while you're pacing.", "label": 0},    
    {"text": "It's frustrating to watch, it really is frustrating to watch. And at some point Driver's going to win the championship and you're going to have a second place player in the championship and celebrating with him, having just beaten Mark.", "label": 0},    
    {"text": "that's kind of, you know, where he's kind of rightfully on the line and putting people up in his importance lessons and stuff.", "label": 0},    
    {"text": "Yeah, once we get to the Cascade truck stop, ask about truck parking for seven tractor", "label": 0},  
    {"text": "The truck is parked on the shoulder of the exit to the rest area.", "label": 0},  
    {"text": "And that's good.", "label": 0},    
    {"text": "Thank you.", "label": 0},    
    {"text": "Alright, that's good.", "label": 0},    
    {"text": "or upload to the firm. So what is my history? What the fuck is going on here?", "label": 0},    
    {"text": "L.A.W. New Orleans.", "label": 0},    
    {"text": "Okay. Uh, er... Actually ignore that one. Okay.", "label": 0},    
    {"text": "Just took a trigger. Yes, swing her out. I already know the details. It's... it's...", "label": 0},    
    {"text": "They're hard dude. Because they're the one length. I kind of regret getting them honestly but once I started to get used to it it's nice but", "label": 0},    
    {"text": "I mean, you said that tonight. Hopefully, if you can get it, you know. Hopefully, if you can get it, you know. Or you can ask on the radio, too.", "label": 0},    
    {"text": "What does that work?", "label": 0},    
    {"text": "Trigger. Done?", "label": 0},    
    {"text": "calendar week three. And then Driver's team has a couple days on calendar week four.", "label": 0},    
    {"text": "Not bad. Maybe we put a ripple into the canvas. Collision mitigation. Ooh, yeah, I'm gonna put a ripple on it. I don't know, hopefully it happens, it'd be cool. But she's like, we don't know because the DTS organization is gonna have to shake up. So, your left side, when you were at like 10 miles an hour, your left side went to zero. Smell that burning rubber?", "label": 0},    
    {"text": "Yeah, that's great. Once we come around on the other side of the loop, you've got Cranky. Once we come around on the other side, go ahead and drop to... over to the left.", "label": 0},    
    {"text": "Thank you, if you want to come ahead and get back in front of us again like you just did, that'd be great.", "label": 0},    
    {"text": "I've been drunk all night, come on and blow me up I'm living in the night, I'm not awake tonight I'm not awake tonight, baby let me take you for a ride Yeah, yeah, yeah, yeah I'm living in the night, I'm not awake tonight Baby let me take you for a ride Yeah, yeah, yeah, yeah Entering the curve Entering the curve", "label": 0},   
    {"text": "On into the night For a clear new day 1965 It's a no- haft", "label": 0},   
    {"text": "That was a good one. I really liked that one though.", "label": 0},   
    {"text": "No, I don't think so. I mean... 30%, not 60, 30%. I mean, I can probably just grade her to 30.", "label": 0},   
    {"text": "Can I get a radio check please? I hear ya.", "label": 0},   
    {"text": "Not? No. I can hear the truck. Yes, I can hear the truck. It could be in there. Truck?", "label": 0},   
    {"text": "It's a 2039 Mississauga tub, a Lexus.", "label": 0},   
    {"text": "Forty-five.", "label": 0},   
    {"text": "Okay, 20...", "label": 0},   
    {"text": "Yep, 16th side.", "label": 0},   
    {"text": "Yeah, 50.", "label": 0},   
    {"text": "55", "label": 0},   
    {"text": "45 sign, yep.", "label": 0},   
    {"text": "45 from that.", "label": 0},   
    {"text": "We're fortunate enough in the Post to have a fantastic polling department of our own. And they had done a poll in 2012 that asked for suspended...", "label": 0},   
    {"text": "That was another good one. Did not, did not gap on that one.", "label": 0}, 
    {"text": "got 5085 calibrated and all that", "label": 0}, 
    {"text": "Go walk in.", "label": 0}, 
    {"text": "Do you want to back up?", "label": 0}, 
    {"text": "Did you see how even though he ran through it still held on? Yeah it did even when he's out. So you see outside of the box it still held on.", "label": 0}, 
    {"text": "Hello? Did you get to the intersection?", "label": 0}, 
    {"text": "That's our mission.", "label": 0}, 
    {"text": "...", "label": 0}, 
    {"text": "That was pretty damn good. That was like almost all me. We got asked to braking but I, yeah I was like, I was just like...", "label": 0}, 
    {"text": "Yeah, I think the launch pad might be under me.", "label": 0}, 
    {"text": "Alright, cool. I'll move it forward maybe another", "label": 0}, 
    {"text": "Very good impact, Wayne. Now it's... Just about six inches behind the front.", "label": 0}, 
    {"text": "I really didn't like the section road though. Yeah, I mean the lines aren't really all that clear. I'm being sarcastic if you're recording this.", "label": 0}, 
    {"text": "for something to pitch about like this, so that's good. Yeah. I was hoping that it would just be pitched, but it's not. It's basically doing the same thing as it was before. It's about as good or bad as it is.", "label": 0}, 
    {"text": "Back once. My resistance is not working. We'll go hospital and have three pop-ups for that.", "label": 0}, 
    {"text": "You want that stretch of road? Yeah, because we were thinking about ending in the future.", "label": 0}, 
    {"text": "You can hear the dere year version ads Yep That's nice", "label": 0}, 
    {"text": "I think it's an interesting name mark. I mean, I've never seen such name marks before. No, I haven't either. I didn't detect them, I don't think.", "label": 0}, 
    {"text": "Now, show the light.", "label": 0}, 
    {"text": "Dude, something like, uh, what was that car in the Valkyrie? That's the one you said you saw in...", "label": 0}, 
    {"text": "Which doesn't seem to work Oh, it does", "label": 0}, 
    {"text": "I just took a trigger on accident. I don't know why I did that. Let's have it. I was trying to release the park brake, and I got a trigger instead.", "label": 0}, 
    {"text": "Why? Because he wants to have a positive example? Or what does it sound like? Yeah, I think it's going to go pretty good like this. Yeah, exactly! What are you eating? It's a chicken! That's a really nice guy, made out of chicken. Is this the most explaining of the car for you? Oh shit, good manuel! I'm going to go for the manuel. You're going to deactivate it. Do we have only to follow him? Try to take off through a multi-lane. You're following him. You're following him.", "label": 0}, 
    {"text": "It's a lot better without the cab, you know. Right. I think you're not expected to get it. You have that drunk driver mentality. I got that on the way. Oh no. Uh... Well, I'm sorry. What's the... I'm thinking you over. Yeah.", "label": 0}, 
    {"text": "ruling over a decision that said no, and recalls and the guidance changed. And so the guidance in 2019 from compliance is that after an auto stop event with the system bringing a vehicle to the standstill, auto hazard lights were allowed only once the standstill was reached. And Ryan said, can you share that? It's not in our understanding. And he should also maybe check with Learman.", "label": 0}, 
    {"text": "I had a yellow challenge. So I'm trying to connect to a Tuesday high of 71, Wednesday high of 70. Next week, pretty much every day is a high of 70. Low of, like, 12. With sunny, warmly growing. So not like gorgeous kayaking weather, but not miserable. Yeah. So, air quality is actually very good.", "label": 0}, 
    {"text": "Trigger. Okay, stop the race.", "label": 0}, 
    {"text": "That's right, that's good. That's good. Alright, I think we can get one more.", "label": 0}, 
    {"text": "So I'm not exactly sure what that was all about. What should have happened is that creep", "label": 0}, 
    {"text": "Then, uh, you want to open up by one note? You want me to keep this going or stop it? Go ahead and stop it. And then open up by one note.", "label": 0}, 
    {"text": "Yeah, it was horrible Definitely rude for a freeway You can hop back in So we'll go around the loop The microwave is going to happen Sorry, to the south loop And do the same thing but have you take the off ramp Because I don't like that Copy Hello, sorry I lost the line", "label": 0}, 
    {"text": "Any more to hit? I got the first alert now. Oh, actually, it might be on the second alert. Alt shift K. Alt shift K. Alt shift K. Alt shift K. Alt shift K. Alt shift K. Alt shift K. Alt shift K. Alt shift K. Alt shift K. Alt shift K.", "label": 0}, 
    {"text": "and tearing up over head is a Cecilia seeing you a Thank you.", "label": 0}, 
    {"text": "But one thing Megan said was that they're thinking pretty seriously about bringing that team moving forward.", "label": 0}, 
    {"text": "We'll have to test hands on too if we can't do it. Alright, test on, test do what? Do a towel. Oh the, okay, gotcha. We're going right alongside them. I know. Are they out of battery or? I don't think so. I think we're doing specific, a speed test. Okay, I'll go 15 kph.", "label": 0}, 
    {"text": "Thanks for watching!", "label": 0},
    {"text": "It is 2.30. Driver, perfectly loved. And before that, Driver. Whom shall I fear? Let's take a look at your forecast today for Central Oregon.", "label": 0}, 
    {"text": "Travels pretty fast.", "label": 0}, 
    {"text": "Beep, beep.", "label": 0}, 
    {"text": "Heartbreak system malfunction, service now, while driving. If we don't have a lot of polls in a primary, then we don't get a report on cab rates. When he was president, things all around were a lot better. It'll just go far in the country when it gets better.", "label": 0}, 
    {"text": "regulators. It's tested by the manufacturers and they say, you know, they say, I swear, right? I swear it's okay. And they put a sticker on.", "label": 0}, 
    {"text": "I have no idea. Aviation. Aviation. Yeah, this happened when I drove around too. I thought it said voice off.", "label": 0},
    {"text": "I'm going to do some moving stuff.", "label": 0},   
    {"text": "Sometimes I think I'm dry Used to clear my head Every time I do", "label": 0},   
    {"text": "and the hotel that boxed your reservation has your passport. You need Lifebox to get your personal info with the address on the screen.", "label": 0},   
    {"text": "So I'll take a trick of that for a car train. ****. That should have been, that was like a clutch closing thing. It was in the process of it, but it was in the process of closing.", "label": 0},   
    {"text": "That one was reassuring. It doesn't do what you're expecting. Well, I mean, that was what it's supposed to be doing, which is not what it's supposed to be doing.", "label": 0},   
    {"text": "Tim would have been proud to see that one. What did he say? He would have been proud to see that one. Tim? I don't know what he said. What was that, David? He said, Tim, my boss's boss, would have been proud to see that one. He got his attention when he started doing stuff like that the other day. Yeah, I'm hoping we can get additional training. You never took the TDD test.", "label": 0},   
    {"text": "Alright, Driver, so if you'll go down there and just pass me, um, like...", "label": 0},   
    {"text": "Okay, you can go ahead and slow down to 50. If you want to go ahead and get ahead of us and go 50, you can.", "label": 0},   
    {"text": "Any changes? Nope. Alright, no, the people's boat is telling me to get from where we find that one. How's Driver at Comdo at the top? Actually, perhaps not Dave, and do you mind coming to the top? Oh, okay. I'm going to go over to the top. I'm going to go over to the top. Okay. I'm going to go over to the top. Okay. Okay.", "label": 0},   
    {"text": "Thank you, go ahead and get back in the car", "label": 0},   
    {"text": "It didn't hit it. I'm taking down that number. Oh, you've been doing it? Where do you save them? Out in the tree. Out on the tree. Nice. What are we saving? One break started.", "label": 0},   
    {"text": "I thought I was going to get the job done Most pleasant place to board in Not sure on what Coming out of a curve", "label": 0},   
    {"text": "I hear a button press.", "label": 0},   
    {"text": "I mean... No, but I...", "label": 0},   
    {"text": "Let's go.", "label": 0},   
    {"text": "Okay, now we can do a mark on this. We're going to mark with some chalk on here to see it light up.", "label": 0},   
    {"text": "And, uh, but, usually scales you just roll through and nothing happens. Yeah. Um...", "label": 0},   
    {"text": "It was a good one. There was a car there.", "label": 0},   
    {"text": "You guys do anything with the acres?", "label": 0},   
    {"text": "No, no, no.", "label": 0},   
    {"text": "What the **** was that dude? What the ****? What the **** was that? Get it out of here. Get it out of here. That was weird. That was a case where...", "label": 0},   
    {"text": "It feels completely other. But I want to break the wall. I don't think so. I think that was all me.", "label": 0},   
    {"text": "Nothing there.", "label": 0},   
    {"text": "Don't press the button. I just did. Well, you need a trigger? Yeah. Don't press any button.", "label": 0},
    {"text": "When in doubt, trigger out. Oh, so you do trigger? Yeah.", "label": 0}, 
    {"text": "0450? 0450? No, 1904 and then that was that.", "label": 0}, 
    {"text": "0720E", "label": 0}, 
    {"text": "You just flip it to neutral. Alright. Is that Duran or?", "label": 0}, 
    {"text": "It's in full snow. No. We'll just keep going. It'll fall down again eventually, probably.", "label": 0}, 
    {"text": "1701 What's the flus for?", "label": 0}, 
    {"text": "9 1851 13 1315 14", "label": 0}, 
    {"text": "10... Yeah, 5 meters.", "label": 0}, 
    {"text": "Uh... Banana", "label": 0}, 
    {"text": "Trigger time 2157.", "label": 0}, 
    {"text": "Trigger time 2037. Yeah, I told Don I was late. Trigger 2037.", "label": 0},    
    {"text": "We got a lot of left yarn. Yeah, I was gonna say, See ya. Ah, fuck it up.", "label": 0}, 
    {"text": "That was our HP issue we had the other day. Oh really? Yeah. Is this the same? Yeah, this is the 6x2.", "label": 0}, 
    {"text": "Even though it just took a few seconds. You can put it down as like head not detected due to something that's not in the video.", "label": 0}, 
    {"text": "For the lighting, I think this is the dome light, the one with the... No, it's ambient light. Whenever you adjust the ambient light,", "label": 0}, 
    {"text": "You watching the road, Mike? Yeah, pretty much. I don't know. Some of the times this thing's going off, I'm not sure.", "label": 0}, 
    {"text": "There, I just took another one. Okay, well, now I know. Now I know what I'm doing. Oh, I saw that. You say, I know.", "label": 0}, 
    {"text": "on a car or on like one of these parkers. 9830 and bring an element of personnel right here.", "label": 0}, 
    {"text": "To say that it was a starting problem.", "label": 0}, 
    {"text": "Yeah, we didn't get that either.", "label": 0}, 
    {"text": "There's a mirror camera menu in the settings on the ICUC, but I can't go into it.", "label": 0}, 
    {"text": "Yeah, I saw it at the top when I saw it.", "label": 0}, 
    {"text": "make any difference to the to the driving stage Yep", "label": 0}, 
    {"text": "Hey Driver.", "label": 0}, 
    {"text": "Yeah, there's the concrete thing.", "label": 0}, 
    {"text": "Both of you put it in manual.", "label": 0}, 
    {"text": "The hop might be the what?", "label": 0}, 
    {"text": "I'm going to test it. You're doing that again now. I had to wait until I plugged it in the dock. Driver did a thing. He did, I thought actually. Isn't that what... That's why Driver took over for 1995, right? I did my days to get up and start talking to interesting subscribers and maybe get in touch with them.", "label": 0}, 
    {"text": "Whoa! What the hell? And breathe deeply, breathe deeply for the old airplane spray in there. I'm sure that's good for animals. Okay, how did it... the brakes felt pretty good on that one. A little... Pretty choppy. Like it was before, but I think it's smoothed out. Yeah, but at least it wasn't doing that. But we're going to try the min, min distance, and that one is probably going to be good.", "label": 0}, 
    {"text": "That's a pass.", "label": 0}, 
    {"text": "I would have been medium to heavy.", "label": 0}, 
    {"text": "Good, perfect. Didn't cancel it. Oh, did I? Good. Try taking it off again. Well, that'll break it for sure, right? Oh, it gave us something else to think about. What did it give us? It doesn't break it. It didn't break it. Oh. Why didn't it break it? Well, we're not in ACC anymore. This is a new one.", "label": 0},
    {"text": "Enjoy downtown Redmond's ladies night with drinks, snacks, and discounts for the ladies. On Saturday, live music featuring Joe Martin and Testimony Wine Bar. For a complete list of events...", "label": 0},
    {"text": "Back. Nope. We got you here. Mike mentioned that. Yeah. First touch. I'll try looking at the back right now. Drop it.", "label": 0},
    {"text": "Here. Got a wait station there, looks like it's open. Really intense for anybody else though.", "label": 0},
    {"text": "I'm rewriting thisui 4223 4223 F", "label": 0},
    {"text": "There's tombstones all around her. Devastating,ٍ Looking good. Your kannibal products were sent. Sorry.", "label": 0},
    {"text": "Interesting, okay. Sounds good. And then my text, um... Driver. Expectivity is reached, generally. Yes, um... There's two issues with that. The one, the problem is just that we can't work. But you also have to try and approach as you can, but one of the most common challenges.", "label": 0},
    {"text": "Not awful. The free-fill is very short. There's still a lot left in the one-tack.", "label": 0},
    {"text": "I've never really, mine is 5th of May but I only end up with like a day, maybe like 3 days I need to figure out what to do with and like I usually get my birthdays in March so I'll like take that off and then I take like a random Friday or something like that", "label": 0},
    {"text": "Is that sound alright? We're already there. We've shot down this road before. Hopefully the guy in front of us gets to take him to the other end. I took a trigger of a red side on the people on the next lane. I'll see you guys. ENA. What was it called? What was it called? What was it called?", "label": 0},
    {"text": "I just like having options. Yeah. Howdy!", "label": 0},
    {"text": "I thought durability would be an issue.", "label": 0},
    {"text": "A lot of people never get a pass on the wind, but it's great hours of weather. I did the same thing to these. I saw this car and it turned on the high beams. Yeah, that's not great.", "label": 0},
    {"text": "I'm just interested about how can we get rid of that aspect and perhaps some rules and you know, the first way to like, go over it, do the rules and then have a little while to sort of break and then when they're out of the race, you know, Intersection ahead you know", "label": 0},

    #ChatGPT generated synthetic data
    {"text": "Noted a slight delay in the auto braking after the lead vehicle decelerated. Possible calibration drift.", "label": 1},
    {"text": "The HMI display didn't show any forward collision warning even though the radar was locked on a decelerating object.", "label": 1},
    {"text": "Trigger box light flashed twice but we didn't get a TTC alert. Might be a wiring issue or missed detection.", "label": 1},
    {"text": "Vehicle decelerated aggressively during ACC handoff. Need to verify if coast mode was engaged before transfer.", "label": 1},
    {"text": "ASCA II event triggered just after lateral maneuver. Marked the timestamp for review.", "label": 1},
    {"text": "Camera feed froze briefly when transitioning from rear to mirror view menu. Possible fault in ICUC firmware.", "label": 1},
    {"text": "Driver input was overridden during the emergency brake test, but system didn't log takeover. Needs debugging.", "label": 1},
    {"text": "Brake pedal feel changed after the second AB trigger. Logging hydraulic response data now.", "label": 1},
    {"text": "Forward target lost momentarily in heavy rain. Lidar stayed active, but radar went soft-fail.", "label": 1},
    {"text": "Handoff between AEB and ACC felt seamless, but the logs still showed an unexpected torque spike.", "label": 1},
    {"text": "Cruise re-engaged without input while coasting downhill. Unexpected behavior.", "label": 1},
    {"text": "Lane keep drifted left during gentle curve. No correction seen.", "label": 1},
    {"text": "Optical alert triggered with no nearby objects. Possible false positive.", "label": 1},
    {"text": "ESC alert came on without traction loss. Sensor check needed.", "label": 1},
    {"text": "Cruise disengaged abruptly after TSR sign passed. No obstruction.", "label": 1},
    {"text": "Excessive brake force applied approaching crest. No target visible.", "label": 1},
    {"text": "Pop-up triggered during sharp curve with no forward vehicle.", "label": 1},
    {"text": "TSR failed to detect temporary signage. Might be occlusion issue.", "label": 1},
    {"text": "Forward radar saw ghost car. Sudden decel event.", "label": 1},
    {"text": "Cruise state transition misfired entering freeway. Logged.", "label": 1},
    {"text": "Voice-off failed to register command. Second attempt successful.", "label": 1},
    {"text": "Reverse maneuver interrupted by unexpected TSR display.", "label": 1},
    {"text": "Intermittent AVA on crest transition. Confirmed trigger.", "label": 1},
    {"text": "Got a weird brake release after coming off the hill, like a little delay in pedal response.", "label": 1},
    {"text": "Trigger for unexpected forward creep. I was in drive but foot was on the brake.", "label": 1},
    {"text": "Right after the merge, ALA veered slightly. Might've misread the lane lines there.", "label": 1},
    {"text": "DMCA activated late. I had already started braking manually by the time it kicked in.", "label": 1},
    {"text": "TTC dropped below threshold, got really close before braking started. Might be worth noting.", "label": 1},
    {"text": "It coasted a bit too far before re-engaging regen. That's inconsistent with previous runs.", "label": 1},
    {"text": "ALA was fighting the crown in the road, kept nudging me left. No oncoming traffic though.", "label": 1},
    {"text": "Got an IPM event when switching from ACC to manual throttle. No driver input for a second.", "label": 1},
    {"text": "Cruise reset again after the pause. Was set at 70, dropped to 65 when I re-engaged.", "label": 1},
    {"text": "Vehicle hesitated before shifting from 2nd to 3rd, like it didn't know what gear to go into.", "label": 1},
    {"text": "Curve handling was super sloppy on that off-camber turn. AVA lost target again mid-turn.", "label": 1},
    {"text": "No torque output during coast phase, even though there was a target. That's odd.", "label": 1},
    {"text": "Pressure test didn't trigger when expected, even though pedal force was definitely above 30N.", "label": 1},
    {"text": "EBA false positive. Got a warning but no actual object in path.", "label": 1},
    {"text": "LEP camera struggled in shadow under that bridge. Misread the white lane as a barrier.", "label": 1},
    {"text": "It dropped out of ACC while following. No alert, just coasted. Weird behavior.", "label": 1},
    {"text": "Trigger for ALA disengage mid-curve. No alert or tone. Could be logging issue too.", "label": 1},
    {"text": "Gear held at 3rd for too long after hill descent. Engine braking felt underutilized.", "label": 1},
    {"text": "Had to nudge the wheel to keep lane center. AVA wasn't holding the radius properly.", "label": 1},
    {"text": "Driver override happened when applying 10% throttle, even though ACC was active.", "label": 1},
    {"text": "Lost target just before the overpass. Reacquired quickly but that gap could be dangerous.", "label": 1},
    {"text": "Steering feedback was grainy after crossing lane markings. Might be related to road texture.", "label": 1},
    {"text": "Driver display showed 'Lane Hold Off' but no indication why. System seemed online.", "label": 1},
    {"text": "ABS kicked in super early on that gravel patch. Probably too sensitive.", "label": 1},
    {"text": "Took a trigger for creep in D-mode. It rolled forward without throttle input.", "label": 1},
    {"text": "Noticed a brief ESC activation on dry pavement. Might've been due to side slope.", "label": 1},
    {"text": "ALA overcompensated coming out of the roundabout. Felt jerky.", "label": 1},
    {"text": "Couldn't detect the lead vehicle in fog until we were inside 40 meters. Poor visibility response.", "label": 1},
    {"text": "Brake hold released a little too early at the red light. Had to reapply manually.", "label": 1},
    {"text": "Triggered a torque reduction event when downshifting manually into 2nd.", "label": 1},
    {"text": "B coast didn't hold even though conditions matched the trigger spec.", "label": 1},
    {"text": "Switching from ALA to manual caused a slight torque dip. Feels rough.", "label": 1},
    {"text": "No alert for cut-in vehicle. It came pretty close before response.", "label": 1},
    {"text": "LKA disengaged when I tapped the brake slightly. Is that expected?", "label": 1},
    {"text": "Okay so trigger, looked like false positive again on left guardrail sensor.", "label": 1},
    {"text": "Vehicle slowed unexpectedly but regained speed after hitting the downhill slope.", "label": 1},
    {"text": "I noticed the ALA correction was late on that curve near the exit ramp.", "label": 1},
    {"text": "There was a sudden lane drift left, no warning before, then trigger went off.", "label": 1},
    {"text": "Cruise reset twice during that run, not sure if it's sensor related or control software.", "label": 1},
    {"text": "Got an unusual IPM event during acceleration phase, might want to check that log.", "label": 1},
    {"text": "Brake override kicked in too late causing a bit of overshoot on the test track.", "label": 1},
    {"text": "Trigger for intermittent loss of forward radar target in heavy traffic.", "label": 1},
    {"text": "Driver assist cut out when entering the tunnel, maybe sensor calibration needed.", "label": 1},
    {"text": "Saw a false positive for pedestrian detection on an empty sidewalk at 8th street.", "label": 1},
    {"text": "We got multiple triggers on that steep left curve, could be traction control issue.", "label": 1},
    {"text": "The vehicle slowed down sharply but the lane keeping was still stable, interesting.", "label": 1},
    {"text": "I think the sensor fusion failed momentarily near that overhead sign, caused hesitation.", "label": 1},
    {"text": "Looks like the adaptive cruise toggled off unexpectedly then back on after 10 seconds.", "label": 1},
     
    {"text": "Are we stopping for lunch soon or just driving through?", "label": 0},
    {"text": "I can't believe we forgot the snacks again. Third time this trip.", "label": 0},
    {"text": "What was that song playing earlier? It had a cool beat.", "label": 0},
    {"text": "The sunset over the mountains looked amazing. Wish I had taken a photo.", "label": 0},
    {"text": "Did you hear that weird noise from the glovebox area? Might just be the coffee cup rattling.", "label": 0},
    {"text": "Remember that diner we stopped at last time? They had killer pancakes.", "label": 0},
    {"text": "Sorry, I zoned out during that whole conversation about brake stuff.", "label": 0},
    {"text": "Mike said he'll be late again. Same as usual, I guess.", "label": 0},
    {"text": "Randomly got an ad for dog food. I don't even own a dog.", "label": 0},
    {"text": "Was that a deer? Or just a mailbox? Kinda looked like it moved.", "label": 0},
    {"text": "Alright folks, coming up next we've got traffic and weather together on the 8s.", "label": 0},
    {"text": "Wait, is that my coffee or yours? I can't tell anymore.", "label": 0},
    {"text": "Can someone mute their mic? I'm hearing a weird echo.", "label": 0},
    {"text": "Do we have the slides from last week's thing? Or was that never sent?", "label": 0},
    {"text": "Okay but hear me out — what if the ducks are organizing?", "label": 0},
    {"text": "You're listening to 104.5, the vibe station — smooth and easy all day.", "label": 0},
    {"text": "I think it's in the drawer? The top one. Or maybe I left it in the car.", "label": 0},
    {"text": "Sorry, I was on mute. Yeah, what I was saying is basically nothing useful.", "label": 0},
    {"text": "So I was like, no way, that's not even how you pronounce 'gyro'!", "label": 0},
    {"text": "Let's circle back on that after lunch, cool?", "label": 0},
    {"text": "Traffic's backed up on the 290 westbound, avoid if you can.", "label": 0},
    {"text": "Can we just skip the intro slide next time? I think we all know who we are.", "label": 0},
    {"text": "Alt shift T. Or wait, maybe it's alt shift R. One of those resets the view.", "label": 0},
    {"text": "Ugh, this update moved everything. I can't find the save button now.", "label": 0},
    {"text": "That's just how he says library like liberry. Every single time.", "label": 0},
    {"text": "Okay, and back to the music — here's something chill for your afternoon slump.", "label": 0},
    {"text": "He said 'vibes are immaculate' and honestly? He wasn't wrong.", "label": 0},
    {"text": "Wait, who's even sharing right now? Is this someone's screen or a demo?", "label": 0},
    {"text": "he keeps taking credit for stuff i did like in front of everyone like what am i supposed to say", "label": 0},
    {"text": "they were whispering in the break room again like right after that email went out", "label": 0},
    {"text": "honestly im not surprised she quit she was working overtime for like three weeks straight", "label": 0},
    {"text": "yeah well he said it wasnt personal but he literally called her out in the meeting", "label": 0}
]
# Here we are training the classifier, taking 80% of the examples as training data and 20% as test data
train_data, test_data = train_test_split(examples, test_size=0.2, random_state=42)
train_dataset = Dataset.from_list(train_data)
test_dataset = Dataset.from_list(test_data)

# Use tokenizer to prepare for classifier model input
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

def preprocess(examples):
    return tokenizer(examples["text"], truncation=True, padding=True)

# apply tokenizer to all entries
train_dataset = train_dataset.map(preprocess, batched=True)
test_dataset = test_dataset.map(preprocess, batched=True)

config = DistilBertConfig.from_pretrained("distilbert-base-uncased", num_labels=2)
config.dropout = 0.2
config.attention_dropout = 0.2
# Load DistilBERT model, Bidirectional Encoder Representations from Transformers, for sequence classification, can help understand the context of words and figure out relationships
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", config=config)


# Use accuracy metric for evaluation (hugging face)
accuracy = evaluate.load("accuracy")
precision = evaluate.load("precision")
recall = evaluate.load("recall")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    f2 = fbeta_score(labels, preds, beta=2)
    acc = accuracy.compute(predictions=preds, references=labels)["accuracy"]
    return {"accuracy": acc, "f2": f2}

# Training arguments
training_args = TrainingArguments(
    output_dir="./classifier_output", 
    per_device_train_batch_size=16, # divide the training dataset into small subsets
    per_device_eval_batch_size=16,
    num_train_epochs=15,
    evaluation_strategy="epoch",
    logging_steps=10,
    learning_rate=2e-5,
    weight_decay=0.01,
    save_strategy="epoch",
    logging_dir="./logs",
    load_best_model_at_end=True,
    metric_for_best_model="f2",
    greater_is_better=True,
    fp16=True
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

# Train the model
trainer.train()

# Evaluate on the test set
eval_results = trainer.evaluate()
print(f"Test accuracy: {eval_results['eval_accuracy']:.2%}")

# Save the model
model.save_pretrained("engineering_classifierV8")
tokenizer.save_pretrained("engineering_classifierV8")

predictions = trainer.predict(test_dataset)
y_true = predictions.label_ids
y_pred = np.argmax(predictions.predictions, axis=1)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Non-Engineering", "Engineering"])
disp.plot(cmap="Blues")
plt.title("Confusion Matrix")
plt.show()